#!/bin/bash
# Isolated simulator app; does not modify project.yml, consume API keys, or build the shared Xcode project.
set -euo pipefail
cd "$(dirname "$0")/../../.."
export DEVELOPER_DIR="${DEVELOPER_DIR:-/Applications/Xcode.app/Contents/Developer}"
export SDKROOT="$(xcrun --sdk iphonesimulator --show-sdk-path)"
: "${CRATE_VERIFY_DEVICE:?Set CRATE_VERIFY_DEVICE to a booted iOS 27.1 simulator UDID}"
build_dir=$(mktemp -d /tmp/crate-teamate2-check.XXXXXX)
trap 'rm -rf "$build_dir"' EXIT
python3 - "$build_dir" <<'PY'
import pathlib, plistlib, shutil, subprocess, sys
root=pathlib.Path.cwd()
build=pathlib.Path(sys.argv[1])
app=build/'Crate.app'
app.mkdir()
source=(root/'Sources/App/CrateApp.swift').read_text().replace('        orchestrator.wire()', '        orchestrator.wire()\n        if ProcessInfo.processInfo.arguments.contains("-crateVerification") { Task { await TeamateChecks.run() } }')
(build/'VerificationApp.swift').write_text(source)
shutil.copy2(root/'Sources/Transfer/Verification/Checks.swift.txt', build/'Checks.swift')
files=[str(p) for p in sorted((root/'Sources').rglob('*.swift')) if p.name != 'CrateApp.swift']
subprocess.run(['xcrun','swiftc','-sdk',__import__('os').environ['SDKROOT'],'-target','arm64-apple-ios27.1-simulator','-swift-version','5','-parse-as-library',*files,str(build/'VerificationApp.swift'),str(build/'Checks.swift'),'-o',str(app/'Crate')],check=True)
p=plistlib.loads((root/'Resources/Info.plist').read_bytes())
p.update(CFBundleExecutable='Crate',CFBundleIdentifier='com.shuhan.crate.teamate2',CFBundleName='Crate',CFBundleShortVersionString='0.1',CFBundleVersion='1',MinimumOSVersion='27.1',CFBundleSupportedPlatforms=['iPhoneSimulator'],UIDeviceFamily=[1])
for key in ['OPENAI_API_KEY','TYPESAFE_API_KEY','REVENUECAT_API_KEY','CRATE_LIBRARY_PATH']: p.pop(key,None)
(app/'Info.plist').write_bytes(plistlib.dumps(p))
for directory in ['Fonts','AI']:
    for file in (root/'Resources'/directory).iterdir():
        if file.is_file(): shutil.copy2(file,app/file.name)
shutil.copytree(root/'Resources/DefaultKit',app/'DefaultKit')
subprocess.run(['codesign','--force','--sign','-',str(app)],check=True)
PY
xcrun simctl terminate "$CRATE_VERIFY_DEVICE" com.shuhan.crate.teamate2 >/dev/null 2>&1 || true
xcrun simctl install "$CRATE_VERIFY_DEVICE" "$build_dir/Crate.app"
container=$(xcrun simctl get_app_container "$CRATE_VERIFY_DEVICE" com.shuhan.crate.teamate2 data)
# Only remove the report generated by this verification app; don't accept a stale pass.
rm -f "$container/Documents/teamate2-checks.txt"
xcrun simctl launch "$CRATE_VERIFY_DEVICE" com.shuhan.crate.teamate2 -crateOffline 1 -crateNoPaywall 1 -crateDebugLog 1 -crateVerification 1
for attempt in {1..45}; do
    if [[ -f "$container/Documents/teamate2-checks.txt" ]]; then
        cat "$container/Documents/teamate2-checks.txt"
        if grep -q '^FAIL' "$container/Documents/teamate2-checks.txt"; then exit 1; fi
        exit 0
    fi
    sleep 1
done
echo 'FAIL: simulator verification timed out' >&2
exit 1
